name: Detect breaking changes

on: push

jobs:
  build:
    name: Detecting breaking changes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: Setup yarn
      run: npm install -g yarn

    - name: Yarn install
      run: yarn install --immutable

    - name: Build packages
      run: yarn packages:build 

    - name: Detect breaking changes
      run: ./scripts/check-breaking-changes.sh 

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ${{ env.BREAKING_CHANGES_MESSAGE }}

    - name: Exit
      run: exit ${{ env.BREAKING_CHANGES_IS_BREAKING }}
      shell: bash

